{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "my-bloody-jenkins.fullname" . }}
  labels:
    app: {{ template "my-bloody-jenkins.name" . }}
    chart: {{ template "my-bloody-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}